kind: Pod
apiVersion: v1
metadata:
  name: networktest
spec:
  restartPolicy: Never
  volumes:
    - name: shared-data
      emptyDir: {}
  containers:
    - name: nginx2c
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
    - name: ubuntu2c
      image: ubuntu
      volumeMounts:
        - name: shared-data
          mountPath: /pod-data
      command: ["/bin/bash","-c","while true; do echo Hi TCS ; sleep 5; done"]
