kind: Pod
apiVersion: v1
metadata:
  name: apachetest2
spec:
  restartPolicy: Never
  volumes:
    - name: shared-data
      emptyDir: {}
  containers:
    - name: apache2c
      image: httpd
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared-data
          mountPath: /var/www/html
    - name: ubuntu2c
      image: ubuntu
      volumeMounts:
        - name: shared-data
          mountPath: /pod-data
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo Apache Implementation; sleep 10; done"]
